# Generated by Django 4.1.1 on 2022-09-14 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('available_quantity', models.IntegerField()),
                ('price_per_unit', models.IntegerField()),
                ('unit', models.CharField(choices=[('kg', 'KG'), ('gm', 'Gram'), ('lr', 'Litre')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.ingrediants')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.menuitems')),
            ],
        ),
    ]
