# Generated by Django 4.1.1 on 2022-09-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0002_purchaselog'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaselog',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
