# Generated by Django 4.1.1 on 2022-09-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0004_alter_ingrediants_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediants',
            name='available_quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingrediants',
            name='unit',
            field=models.CharField(choices=[('kg', 'KG'), ('gm', 'Gram'), ('lr', 'Litre'), ('ou', 'Ounces'), ('eg', 'Eggs'), ('lb', 'lbs')], max_length=2),
        ),
    ]
