# Generated by Django 4.0.1 on 2022-09-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0005_alter_ingrediants_available_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperequirements',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
