# Generated by Django 4.0.1 on 2022-09-15 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0006_reciperequirements_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingrediants',
            options={'verbose_name_plural': 'Ingrediants'},
        ),
        migrations.AlterModelOptions(
            name='menuitems',
            options={'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterModelOptions(
            name='reciperequirements',
            options={'verbose_name_plural': 'Recipe Requirements'},
        ),
        migrations.RemoveField(
            model_name='purchaselog',
            name='quantity',
        ),
    ]
